### ISSUE TITLE
replace toFixed with dot.Util.toFixed?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/kite#50]
This sim uses JavaScript's built-in toFixed. This function should not be used directly; it is notoriously buggy, and behavior differs depending on browser, because the spec doesn't specify whether to round or floor. Should we be using dot.Util.toFixed instead?

**Comment by jonathanolson** [comment]
It's only used for 20 decimal places, the rounded result isn't displayed to users (just for setting SVG element properties, since it doesn't support scientific notation syntax), and it's in a place that could potentially cause a bottleneck in certain types of Scenery operations.

I have a slight preference for built-in toFixed just because it is probably faster, but I'd like to get your opinion. I'm fine documenting the above requirements and reasoning above if we stay with the built-in toFixed.

**Comment by pixelzoom** [comment]
Documenting the requirement sounds fine.

**Comment by jonathanolson** [comment]
Documented.
