### ISSUE TITLE
add visibility annotations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/kite#52]
Add a @public, @protected or @private annotation to anything that's publicly visible.
See https://github.com/phetsims/tasks/issues/307.

**Comment by marlitas** [comment]
Kite is 59% converted to typescript and the remaining javascript files looked to have visibility annotations on a quick skim.

Due to our commitment to convert to typescript and the new type error that requires visibility annotations I fee like this issue can be closed. Please feel free to re-open if someone feels differently.
